name: action_playground
on: 
  push:
    branches:
      - "**"
jobs:
  set-up-python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set-up python 3.8.5
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
          architecture: 'x64'
      
      - name: Echo python version
        run: python3 --version
  
  pytest-unit-test-job:
    needs: set-up-python-job
    runs-on: ubuntu-latest
    steps:
      - name: Set-up python 3.8.5
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
          architecture: 'x64'
      - name: Install pytest
        run: |
               echo create virtual environment
               python3 -m venv ~/.venv/M3m8p5
               source ~/.venv/M3m8p5/bin/activate
      - name: Run pytest
        run: |
              pip install pytest
              echo pytest installed
              echo run pytest
              ls
              pytest
              echo unit test run completed
            